services:
  - type: web
    name: webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://kavinprabakaran64:WXVaCOwLQIJ5KPbe@cluster0.u3ynomd.mongodb.net/github_events?retryWrites=true&w=majority&tls=true
    build:
      pythonVersion: 3.10.13

